services:
    server:
        build:
            context: ./server # <-- new location for Dockerfile
            dockerfile: Dockerfile # optional if it's named Dockerfile by default
        ports:
            - "3000:3000" # keep this if your Express app runs on 3000
        environment:
            - PORT=3000
            - MONGO_URI=mongodb://mongodb:27017/test-db
        depends_on:
            - mongodb
        command: npm start
    client:
        build:
            context: ./client
        ports:
            - "81:80"
        depends_on:
            - server
    mongodb:
        image: mongo:4.4.18
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: unless-stopped
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_BASICAUTH: "false"
            ME_CONFIG_SITE_BASEURL: /db/
        depends_on:
            - mongodb

volumes:
    mongo_data:
