services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
            - MONGO_URI=mongodb://mongodb:27017/test-db
        depends_on:
            - mongodb
        command: npm start
    mongodb:
        image: mongo:4.4.18
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
volumes:
    mongo_data:
